### PR TITLE
Link to website

### PR DESCRIPTION
**Pull request by JjTheHusky**
Added a link to the main DISE website and such.

Also as a side question, perhaps a wiki page could be created to show how to use DISE? Either GitHub wiki or something else externally.

### CODE REVIEW

**Comment by SteffenL** [comment]
Thanks for the PR!

Turns out that `https://` is not working at the moment for the website so I'll need to fix that too later.

Opening a wiki or something for DISE is certainly a good idea to avoid losing a lot of the tips and tricks on using DISE! A wiki on GitHub would work fine, and another idea is to just use GitHub Pages for this.

**Comment by JjTheHusky** [comment]
I noticed that there wasn't any use of https, hopefully that can be fixed soon!

In regards to the wiki, I don't believe I can create any wiki pages/github pages without permissions :(

**Comment by SteffenL** [comment]
I have set up the `docs` directory for GH pages so that it is possible to contribute.

**Comment by SteffenL** [comment]
As ugly as it is, this is what I have right now: https://steffenl.github.io/dise/

Tracking the setup process in #14.

**Pull request merged**
